# <font color = 'orange'> Numpy - Part 4

---

### Sort , search and counting functions

In [1]:
import numpy as np 

In [2]:
arr = np.array([6,3,8,2,1,9,5])
arr

array([6, 3, 8, 2, 1, 9, 5])

In [3]:
np.sort(arr)

array([1, 2, 3, 5, 6, 8, 9])

In [4]:
# it will give the position for the element so that we can insert there to make the array as sorted
np.searchsorted(arr,7)

5

In [5]:
arr1 = np.array([0,324,645,65,6,6,0,0,0,234])
arr1

array([  0, 324, 645,  65,   6,   6,   0,   0,   0, 234])

In [6]:
# to count the non null value 
np.count_nonzero(arr1)

6

In [7]:
np.where(arr1 > 0)

(array([1, 2, 3, 4, 5, 9], dtype=int64),)

In [8]:
np.extract(arr1 > 2 , arr1)

array([324, 645,  65,   6,   6, 234])

---

### Byte swapping

In [9]:
arr

array([6, 3, 8, 2, 1, 9, 5])

In [10]:
arr.byteswap(inplace = True)

array([100663296,  50331648, 134217728,  33554432,  16777216, 150994944,
        83886080])

In [11]:
arr

array([100663296,  50331648, 134217728,  33554432,  16777216, 150994944,
        83886080])

---

### Copies and views

In [12]:
arr1

array([  0, 324, 645,  65,   6,   6,   0,   0,   0, 234])

In [13]:
# deep copy
a = np.copy(arr1)
a

array([  0, 324, 645,  65,   6,   6,   0,   0,   0, 234])

In [14]:
# view - shallow
# it is same as of 
b = arr1.view()
b

array([  0, 324, 645,  65,   6,   6,   0,   0,   0, 234])

In [15]:
b[0] = 34
print(arr1)
print(b)

[ 34 324 645  65   6   6   0   0   0 234]
[ 34 324 645  65   6   6   0   0   0 234]


---

### Matrix library

In [16]:
import numpy.matlib as nm

In [17]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [18]:
nm.ones(5)

matrix([[1., 1., 1., 1., 1.]])

In [19]:
# identity matrix
nm.eye(5)

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

---

### Linear algebra

In [20]:
arr1 = np.random.randint([[2,3],[4,5]])
arr1

array([[1, 0],
       [1, 1]])

In [21]:
arr2 = np.random.randint([[5,3] , [2,5]])
arr2

array([[1, 0],
       [1, 4]])

In [22]:
# dot product
np.dot(arr1,arr2)

array([[1, 0],
       [2, 4]])

In [23]:
arr1 @ arr2

array([[1, 0],
       [2, 4]])

---