# <font color = 'orange'> Tensorflow

---

In [1]:
import tensorflow as tf

print("TensorFlow version: {}".format(tf.__version__))
print("Eager execution is: {}".format(tf.executing_eagerly()))

TensorFlow version: 2.14.0
Eager execution is: True


---

### GPU / CPU Check

In [2]:
if tf.test.is_gpu_available():
    print('Running on GPU')
else:
    print('Running on CPU')

Instructions for updating:
Use `tf.config.list_physical_devices('GPU')` instead.


Running on CPU


---

### Tensor Constant

In [3]:
ineuron = tf.constant(42)

ineuron

<tf.Tensor: shape=(), dtype=int32, numpy=42>

In [4]:
ineuron.numpy()

42

In [5]:
a = tf.constant(12, dtype = tf.int64)
a

<tf.Tensor: shape=(), dtype=int64, numpy=12>

In [6]:
b = tf.constant([[4,2],[9,5]])

print(b)

tf.Tensor(
[[4 2]
 [9 5]], shape=(2, 2), dtype=int32)


In [7]:
# extracting only the values

b.numpy()

array([[4, 2],
       [9, 5]], dtype=int32)

In [8]:
# data type and shape

print(b.dtype)
print(b.shape)

<dtype: 'int32'>
(2, 2)


---

### Generating constant

In [9]:
print(tf.ones(shape = (2, 3)))

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)


In [10]:
print(tf.zeros(shape = (3,2)))

tf.Tensor(
[[0. 0.]
 [0. 0.]
 [0. 0.]], shape=(3, 2), dtype=float32)


### Operation of tensors

In [11]:
const1 = tf.constant([[3,4,5],[7,6,4]])
const2 = tf.constant([[1,2,3],[9,8,7]])

result = tf.add(const1, const2)

print(result)

tf.Tensor(
[[ 4  6  8]
 [16 14 11]], shape=(2, 3), dtype=int32)


---

### Random Constant

In [12]:
tf.random.normal(shape = (2, 2), mean = 0, stddev = 1.0)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.19670331,  0.55860776],
       [-1.6667073 ,  0.08366495]], dtype=float32)>

In [13]:
tf.random.uniform(shape = (2, 2), minval = 0, maxval = 10, dtype = tf.int32)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[5, 5],
       [7, 1]], dtype=int32)>

---

### Variables

In [14]:
var0 = 24 # python variable
var1 = tf.Variable(42) # tensor variable of rank 0
var2 = tf.Variable([[[0., 1., 2.], [3., 4., 5.]], [[6.,7., 8.],[9., 10., 11.]]])

var0, var1, var2

(24,
 <tf.Variable 'Variable:0' shape=() dtype=int32, numpy=42>,
 <tf.Variable 'Variable:0' shape=(2, 2, 3) dtype=float32, numpy=
 array([[[ 0.,  1.,  2.],
         [ 3.,  4.,  5.]],
 
        [[ 6.,  7.,  8.],
         [ 9., 10., 11.]]], dtype=float32)>)

### Rank basically denotes the dimension
#### Image is a rank 3 tensor.
#### Video is a rank 4 tensor which is a collection of images(rank 3 tensor).

---

In [15]:
# reassigning new value to the variable
var = tf.Variable(89.)
print(var)

var.assign(23.)
print(var)

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=89.0>
<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=23.0>


In [16]:
intial_value = tf.random.normal(shape = (2, 2))
a = tf.Variable(intial_value)

print(intial_value,'\n')
print(a)

tf.Tensor(
[[-0.2440914   0.99545836]
 [-0.7273437  -0.06828362]], shape=(2, 2), dtype=float32) 

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[-0.2440914 ,  0.99545836],
       [-0.7273437 , -0.06828362]], dtype=float32)>


---

We can assign "=" with assign (value), or assign_add (value) with "+ =", or assign_sub (value) with "-="

In [17]:
new_value = tf.random.normal(shape = (2, 2))
a.assign(new_value)

for i in range(2):
    for j in range(2):
        assert a[i, j] == new_value[i, j] # if the value are different we will get a error

In [18]:
added_value = tf.random.normal(shape = (2, 2))
# for a add added_value
a.assign_add(added_value)

for i in range(2):
    for j in range(2):
        assert a[i, j] == (new_value[i, j] + added_value[i, j]) # assert is like a if condition

---

### Shaping a tensor
* Architecture of the deep learning are very shape specific.
* ex: In ANN, the input is only 1d tensor.

In [19]:
# tensor of rank 3 i.e 3d tensor
tensor = tf.Variable( [ [[0., 1., 2., 5.], [3., 4., 5., 6.]], [[0., 1., 2., 7.], [3., 4., 5., 8.]], [[6., 7., 8., 5.], [9., 10., 11., 5.]] ])

# denotes that  4 columns, 2 rows and 3 2d-tensor
print(tensor.shape)

(3, 2, 4)


---

#### Tensors may be reshaped and retain the same values, as is often required for constructing neural networks.


In [20]:
# while reshaping we need to have number of elements same in original and reshaped tensor
tensor1 = tf.reshape(tensor, [6, 4])
tensor2 = tf.reshape(tensor, [1, 24])

print(tensor1, '\n')
print(tensor2)

tf.Tensor(
[[ 0.  1.  2.  5.]
 [ 3.  4.  5.  6.]
 [ 0.  1.  2.  7.]
 [ 3.  4.  5.  8.]
 [ 6.  7.  8.  5.]
 [ 9. 10. 11.  5.]], shape=(6, 4), dtype=float32) 

tf.Tensor(
[[ 0.  1.  2.  5.  3.  4.  5.  6.  0.  1.  2.  7.  3.  4.  5.  8.  6.  7.
   8.  5.  9. 10. 11.  5.]], shape=(1, 24), dtype=float32)


---

### Ranking (dimensions) of a tensor
The rank of a tensor is the number of dimensions it has, that is, the number of indices that are required to specify any particular element of that tensor.

In [21]:
# rank denotes dimension
print(tf.rank(tensor1), '\n')
print(tf.rank(tensor1).numpy())

tf.Tensor(2, shape=(), dtype=int32) 

2


In [22]:
# shape denotes the scaler values
print(tf.shape(tensor1), '\n')
print(tf.shape(tensor1).numpy())

tf.Tensor([6 4], shape=(2,), dtype=int32) 

[6 4]


---

In [23]:
tensor

<tf.Variable 'Variable:0' shape=(3, 2, 4) dtype=float32, numpy=
array([[[ 0.,  1.,  2.,  5.],
        [ 3.,  4.,  5.,  6.]],

       [[ 0.,  1.,  2.,  7.],
        [ 3.,  4.,  5.,  8.]],

       [[ 6.,  7.,  8.,  5.],
        [ 9., 10., 11.,  5.]]], dtype=float32)>

In [24]:
# to accessing element in the tensor

num = tensor[1, 0, 2]
num

<tf.Tensor: shape=(), dtype=float32, numpy=2.0>

---

### Type casting tensor to numpy or python variable.

In [25]:
print(tensor.numpy())

[[[ 0.  1.  2.  5.]
  [ 3.  4.  5.  6.]]

 [[ 0.  1.  2.  7.]
  [ 3.  4.  5.  8.]]

 [[ 6.  7.  8.  5.]
  [ 9. 10. 11.  5.]]]


In [26]:
print(tensor[1, 0, 2].numpy())

2.0


---

### Finding the size of a tensor

In [27]:
tensor_size = tf.size(input = tensor).numpy()
tensor_size

24

In [28]:
# getting the data type of the variable

tensor_size.dtype

dtype('int32')

---

### Tensorflow mathematical operations

In [29]:
a = tf.random.normal(shape = (2, 2))
b = tf.random.normal(shape = (2, 2))

c = a + b
d = tf.square(c)
e = tf.exp(c)

print(a,'\n')
print(b,'\n')
print(c,'\n')
print(d,'\n')
print(e)

tf.Tensor(
[[-0.8126632   1.2654755 ]
 [ 0.5801496  -0.16011493]], shape=(2, 2), dtype=float32) 

tf.Tensor(
[[-0.01448598  0.13252233]
 [-2.7305956  -2.3123646 ]], shape=(2, 2), dtype=float32) 

tf.Tensor(
[[-0.82714915  1.3979979 ]
 [-2.150446   -2.4724796 ]], shape=(2, 2), dtype=float32) 

tf.Tensor(
[[0.6841757 1.954398 ]
 [4.624418  6.1131554]], shape=(2, 2), dtype=float32) 

tf.Tensor(
[[0.43729416 4.047089  ]
 [0.11643223 0.08437538]], shape=(2, 2), dtype=float32)


In [30]:
# element wise tensor
tensor * tensor

<tf.Tensor: shape=(3, 2, 4), dtype=float32, numpy=
array([[[  0.,   1.,   4.,  25.],
        [  9.,  16.,  25.,  36.]],

       [[  0.,   1.,   4.,  49.],
        [  9.,  16.,  25.,  64.]],

       [[ 36.,  49.,  64.,  25.],
        [ 81., 100., 121.,  25.]]], dtype=float32)>

---

### Broadcasting

In [31]:
print(tensor.numpy())

[[[ 0.  1.  2.  5.]
  [ 3.  4.  5.  6.]]

 [[ 0.  1.  2.  7.]
  [ 3.  4.  5.  8.]]

 [[ 6.  7.  8.  5.]
  [ 9. 10. 11.  5.]]]


In [32]:
# if a tensor is multiplied by the scaler then each element will be multiplied with a scaler

tensor4 = tensor * 4
print(tensor4.numpy())

[[[ 0.  4.  8. 20.]
  [12. 16. 20. 24.]]

 [[ 0.  4.  8. 28.]
  [12. 16. 20. 32.]]

 [[24. 28. 32. 20.]
  [36. 40. 44. 20.]]]


---

### Transpose matrix multiplication

In [33]:
matrix_u = tf.constant([[3, 4, 3]])
matrix_v = tf.constant([[1, 2, 1]])

n = tf.matmul(matrix_u, tf.transpose(matrix_v))
print(n.numpy())

[[14]]


---

### Casting tensor to another data type

In [34]:
print(tensor1, '\n')

i = tf.cast(tensor1, dtype = tf.int32)

print(i)

tf.Tensor(
[[ 0.  1.  2.  5.]
 [ 3.  4.  5.  6.]
 [ 0.  1.  2.  7.]
 [ 3.  4.  5.  8.]
 [ 6.  7.  8.  5.]
 [ 9. 10. 11.  5.]], shape=(6, 4), dtype=float32) 

tf.Tensor(
[[ 0  1  2  5]
 [ 3  4  5  6]
 [ 0  1  2  7]
 [ 3  4  5  8]
 [ 6  7  8  5]
 [ 9 10 11  5]], shape=(6, 4), dtype=int32)


In [35]:
# casting will truncate the decimal value
tf.cast(tf.constant(4.8), dtype = tf.int32)

<tf.Tensor: shape=(), dtype=int32, numpy=4>

---

### Declaring ragged tensors (in NLP)
A ragged tensor is a tensor with one or more ragged dimensions. Ragged dimensions are dimensions that have slices that may have different lengths.There are a variety of methods for declaring ragged arrays, the simplest being a constant ragged
array.

In [36]:
# shows how to delcare a constant ragged arrary and the lengths of the individual slices

# ragged tensor have different number of element in different direction
ragged = tf.ragged.constant([ [5, 2, 6, 1], [], [4, 19, 3], [8], [9,2] ])

print(ragged, '\n')
print(ragged[0, :])
print(ragged[0, :].shape, '\n')

print(ragged.shape)

<tf.RaggedTensor [[5, 2, 6, 1], [], [4, 19, 3], [8], [9, 2]]> 

tf.Tensor([5 2 6 1], shape=(4,), dtype=int32)
(4,) 

(5, None)


---

### Finding squared difference between two tensors

In [37]:
varx = [1, 3, 5, 7, 11]
vary = 5

varz = tf.math.squared_difference(varx, vary)
varz

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([16,  4,  0,  4, 36], dtype=int32)>

---

### Find the mean across all axes

In [38]:
numbers = tf.constant( [[4., 5.], [7., 3.]] )

tf.reduce_mean(input_tensor = numbers)

<tf.Tensor: shape=(), dtype=float32, numpy=4.75>

In [39]:
# taking mean across rows is like compressing columns
tf.reduce_mean(input_tensor = numbers, axis = 1)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([4.5, 5. ], dtype=float32)>

In [40]:
# taking mean across column is like compressing rows
tf.reduce_mean(input_tensor = numbers, axis = 0)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([5.5, 4. ], dtype=float32)>

In [41]:
# we can maintain the dimension of the array
tf.reduce_mean(input_tensor = numbers, axis = 0, keepdims = True) # we get the 2d array as output

<tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[5.5, 4. ]], dtype=float32)>

---

In [42]:
# setting value is to recall the random generated values
# even if we run random variable multiple times we get the same value as we got in the first random generated values

tf.random.set_seed(11)
ran1 = tf.random.uniform(shape = (2, 2), maxval = 10, dtype = tf.int32)
ran2 = tf.random.uniform(shape = (2, 2), maxval = 10, dtype = tf.int32)

# if we not set the seed value then every time when we run the code will give the different values
print(ran1, '\n')
print(ran2)

tf.Tensor(
[[4 6]
 [5 2]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[9 7]
 [9 4]], shape=(2, 2), dtype=int32)


---

Example : Random values generating for the dice

In [43]:
tf.random.set_seed(None) # everytime we generate we get a random value

dice1 = tf.random.uniform(shape = [10, 1], minval = 1, maxval = 7, dtype = tf.int32)
dice2 = tf.random.uniform(shape = [10, 1], minval = 1, maxval = 7, dtype = tf.int32)

# sum of the output
dice_sum = dice1 + dice2

resulting_sum = tf.concat(values = [dice1 , dice2, dice_sum], axis = 1)

print(resulting_sum)

tf.Tensor(
[[ 5  6 11]
 [ 2  3  5]
 [ 4  4  8]
 [ 6  1  7]
 [ 2  1  3]
 [ 2  6  8]
 [ 1  2  3]
 [ 6  1  7]
 [ 2  5  7]
 [ 1  3  4]], shape=(10, 3), dtype=int32)


---

We can find the **index** of the max or min value in an array.
    
>`tf.argmax(input, axis=None, name=None, output_type=tf.int64 )`

>`tf.argmin(input, axis=None, name=None, output_type=tf.int64 )`

In [44]:
# 1-D tensor
t5 = tf.constant([2, 11, 5, 42, 7, 19, -6, -11, 29])
print(t5.numpy(),'\n')

i = tf.argmax(input=t5).numpy()
print('index of max; ', i)
print('Max element: ',t5[i].numpy(),'\n')

i = tf.argmin(input=t5,axis=0).numpy()
print('index of min: ', i)
print('Min element: ',t5[i].numpy(),'\n')

print('-'.center(30, '-'))

# 2D tensor
t6 = tf.reshape(t5, [3,3])
print(t6.numpy(),'\n')

i = tf.argmax(input=t6,axis=0).numpy() # max arg down rows
print('indices of max down rows; ', i,'\n')

i = tf.argmin(input=t6,axis=0).numpy() # min arg down rows
print('indices of min down rows ; ',i,'\n')


i = tf.argmax(input=t6,axis=1).numpy() # max arg across cols
print('indices of max across cols: ',i,'\n')

i = tf.argmin(input=t6,axis=1).numpy() # min arg across cols
print('indices of min across cols: ',i,'\n')

[  2  11   5  42   7  19  -6 -11  29] 

index of max;  3
Max element:  42 

index of min:  7
Min element:  -11 

------------------------------
[[  2  11   5]
 [ 42   7  19]
 [ -6 -11  29]] 

indices of max down rows;  [1 0 2] 

indices of min down rows ;  [2 2 0] 

indices of max across cols:  [1 0 2] 

indices of min across cols:  [0 1 1] 



---

### Saving and restoring tensor values using a checkpoint

In [45]:
variable = tf.Variable([[1,3,4,7],[11,13,26,67]])

checkpoint = tf.train.Checkpoint(var = variable)
save_path = checkpoint.save('./vars')

variable.assign([[0,0,0,0],[0,0,0,0]])
print(variable,'\n')

checkpoint.restore(save_path)
print(variable)

<tf.Variable 'Variable:0' shape=(2, 4) dtype=int32, numpy=
array([[0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int32)> 

<tf.Variable 'Variable:0' shape=(2, 4) dtype=int32, numpy=
array([[ 1,  3,  4,  7],
       [11, 13, 26, 67]], dtype=int32)>


---

### Using tf.function

tf.function is a function that will take a Python function and return a TensorFlow graph. The
advantage of this is that graphs can apply optimizations and exploit parallelism in the Python
function (func). tf.function is new to TensorFlow 2.


Its signature is as follows:
    
`tf.function(
func=None,
input_signature=None,
autograph=True,
experimental_autograph_options=None
)`


In [46]:
def fun1(x, y):
    return tf.reduce_mean(input_tensor = (tf.multiply(x**2, 5) + y**2))

tensor_fun1 = tf.function(fun1)
x = tf.constant([4., -5.])
y = tf.constant([2., 3.])

# tensor_fun1 executes as a tensorflow graph
assert (fun1(x, y).numpy()) == (tensor_fun1(x, y).numpy())
# if there is no output means that assert passes

In [47]:
sum = sum((([4**2, 5**2]) * 5 + ([2**2, 3**2])))
mean = sum / 2
mean

109.0

In [48]:
tensor_fun1(x, y).numpy()

109.0

---

## Calculate the gradient

* Another difference from numpy is that it can automatically track the gradient of any variable.

* Open one GradientTape and `tape.watch()` track variables through

In [49]:
a = tf.random.normal(shape = (2, 2))
b = tf.random.normal(shape = (2, 2))

# in deep the gradient calculation is done in similar way
with tf.GradientTape() as tape:
    tape.watch(a)
    c = tf.sqrt(tf.square(a) + tf.square(b))
    # we get the gradient when we differentiate c w.r.t a
    dc_da = tape.gradient(c, a)
    print(dc_da)

tf.Tensor(
[[-0.9850783   0.9996131 ]
 [-0.9338319   0.99336797]], shape=(2, 2), dtype=float32)


In [50]:
a = tf.Variable(a)

with tf.GradientTape() as tape:
    # no need to watch for a tensorflow variable
    c = tf.sqrt(tf.square(a) + tf.square(b))
    dc_da = tape.gradient(c, a) # derivative
    print(dc_da)

tf.Tensor(
[[-0.9850783   0.9996131 ]
 [-0.9338319   0.99336797]], shape=(2, 2), dtype=float32)


In [51]:
# Calculating the double derivative
with tf.GradientTape() as outer_tape:
    with tf.GradientTape() as inner_tape:
        c = tf.sqrt(tf.square(a) + tf.square(b))
        dc_da = inner_tape.gradient(c, a) # derivative
    d2c_d2a = outer_tape.gradient(dc_da, a) # double derivative
    print(d2c_d2a)

tf.Tensor(
[[0.05604315 0.00064939]
 [0.10877085 0.00868458]], shape=(2, 2), dtype=float32)


---

## <font color='blue'> Remaining we have already seen the Keras API which is built on tensorflow.

---