# <font color = 'orange'> Assignment 18 Solutions

---

### Consider the below code to answer further questions:
#### import numpy as np
#### list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]
#### array_list = np.array(object = list_)
### Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.

#### Answer: Yes, list_ is the normal list data type and the array_list is the numpy ndarray.

In [1]:
import numpy as np
list_ = ['1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)
print(type(list_))
print(type(array_list))

<class 'list'>
<class 'numpy.ndarray'>


---

### Q2. Write a code to print the data type of each and every element of both the variables list_ and arra_list.

In [2]:
for i in list_:
    print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [3]:
for i in array_list:
    print(type(i))

<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


---

### Q3. Considering the following changes in the variable, array_list:
#### array_list = np.array(object = list_, dtype = int)
### Will there be any difference in the data type of the elements present in both the variables, num_list and num_array? If so then print the data types of each and every element present in both the variables, num_list and num_array.
#### Consider the below code to answer further questions:
#### import numpy as np
#### num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
#### num_array = np.array(object = num_list)

#### Answer : Yes there is difference between the data type of the both because num_list is an integer and num_array is numpy's 32byte integer 

In [4]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)
print(num_list)
print(num_array)

[[1, 2, 3], [4, 5, 6]]
[[1 2 3]
 [4 5 6]]


In [5]:
for i in num_list:
    for j in i:
        print(type(j))

<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>


In [6]:
for i in num_array:
    for j in i:
        print(type(j))

<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>


---

### Q4. Write a code to find the following characteristics of variable, num_array: (i) shape (ii) size

In [7]:
arr = np.random.randint(1,10,(4,3))
print(arr)
# shape gives the dimension of the numpy array.
print(arr.shape)
# size gives the number of elements present in the numpy array.
print(arr.size)

[[3 1 6]
 [4 3 1]
 [4 6 8]
 [3 6 4]]
(4, 3)
12


---

### Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.
#### [Hint: The size of the array will be 9 and the shape will be (3,3).]

In [8]:
arr1 = np.zeros((3,3))
print(arr1)
print(arr1.size)
print(arr1.shape)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
9
(3, 3)


---

### Q6. Create an identity matrix of shape (5,5) using numpy functions?
#### [Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [9]:
arr3 = np.eye(5 , dtype = 'int8')
print(arr3)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


---