# <font color = 'orange'> Numpy - Part 1

---

In [1]:
import numpy as np

In [2]:
l = [1,2,3,4]
print(l)
print(type(l))

[1, 2, 3, 4]
<class 'list'>


### Type of creating numpy array.
* arr = np.array(list)
* arr = np.asarray(list)

In [3]:
# 1. using array function
arr1 = np.array(l)
print(arr1)
print(type(arr1))

[1 2 3 4]
<class 'numpy.ndarray'>


In [4]:
arr2 = np.asarray(l)
print(arr2)
print(type(arr2))

[1 2 3 4]
<class 'numpy.ndarray'>


In [5]:
l2 = [[1,2,3] , [2,3,4]]
arr3 = np.array(l2)
print(arr3)
print(type(arr3))

[[1 2 3]
 [2 3 4]]
<class 'numpy.ndarray'>


### To get dimension of the array -> arr.ndim

In [6]:
print(arr2.ndim)
print(arr3.ndim)

1
2


### To create the matrix -> np.matrix(l)

In [7]:
# 2D array => matrix
mat = np.matrix(l)
print(mat)
print(mat.ndim)

[[1 2 3 4]]
2


### To create array another method -> arr = np.asanyarray(list or matrix)

In [8]:
arr5 = np.asanyarray(l)
arr6 = np.asanyarray(mat)
print(arr5)
print(arr5.ndim)
print(arr6)
print(arr6.ndim)

[1 2 3 4]
1
[[1 2 3 4]]
2


---

### Same reference - Pool

In [9]:
arr7 = arr5
print('Shallow copy.')

print(arr5)
print(arr7)

print()
arr5[0] =34

print(arr5)
print(arr7)

Shallow copy.
[1 2 3 4]
[1 2 3 4]

[34  2  3  4]
[34  2  3  4]


In [10]:
# To avoid data manipulation
# with 1D array 
arr8 = arr5.copy()
print('Shallow copy.')

print(arr5)
print(arr8)

print()
arr5[0] = 23

print(arr5)
print(arr8)

Shallow copy.
[34  2  3  4]
[34  2  3  4]

[23  2  3  4]
[34  2  3  4]


### Shallow copy 

In [11]:
# with 2D array 
arr10 = np.copy(arr3)
print('Shallow copy.')

print(arr3)
print(arr10)

print()
arr3[0][1] = 12

print(arr3)
print(arr10)

Shallow copy.
[[1 2 3]
 [2 3 4]]
[[1 2 3]
 [2 3 4]]

[[ 1 12  3]
 [ 2  3  4]]
[[1 2 3]
 [2 3 4]]


### Deep Copy

In [12]:
# with 2D array 
import copy
arr11 = copy.deepcopy(arr3)
print('Deep copy.')

print(arr3)
print(arr11)

print()
arr11[0][1] = 8

print(arr3)
print(arr11)

Deep copy.
[[ 1 12  3]
 [ 2  3  4]]
[[ 1 12  3]
 [ 2  3  4]]

[[ 1 12  3]
 [ 2  3  4]]
[[1 8 3]
 [2 3 4]]


---

### Some functions - np.fromfunction(function,dimension)

In [13]:
a1 = np.fromfunction(lambda i,j : i==j , (3,3))
print(a1)

[[ True False False]
 [False  True False]
 [False False  True]]


In [14]:
a2 = np.fromfunction(lambda i,j : i+j , (3,3))
print(a2)

[[0. 1. 2.]
 [1. 2. 3.]
 [2. 3. 4.]]


---

### foriter(generator function , data type) 

In [15]:
iterable = (i*i for i in range(1,5))
print(iterable)
print(type(iterable))

<generator object <genexpr> at 0x0000022D4F1F0740>
<class 'generator'>


In [16]:
np.fromiter(iterable,float)

array([ 1.,  4.,  9., 16.])

---

In [17]:
b1 = np.fromstring('2 3 5 1',sep=' ')
print(b1)
b1 = np.fromstring('2 3 5 1',sep=' ',dtype=int)
print(b1)

[2. 3. 5. 1.]
[2 3 5 1]


In [18]:
b2 = np.fromstring('2,3,5,1',sep=',')
print(b2)

[2. 3. 5. 1.]


---

### ndim -> gives the dimension.
### size -> gives number of elements of the array.
### shape -> gives the shape of the array.

In [19]:
c1 = np.array([[1,2,3],[7,8,9]])
print(c1)
print('Dimension :',c1.ndim)
print('Number of elements :',c1.size)
print('Shape of the array :',c1.shape)

[[1 2 3]
 [7 8 9]]
Dimension : 2
Number of elements : 6
Shape of the array : (2, 3)


---