# <font color = 'orange'> Numpy - Part 2

---

In [1]:
import numpy as np 

In [2]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [3]:
# range takes only integer
list(range(0.4,30.4))

TypeError: 'float' object cannot be interpreted as an integer

#### np.arange(start , end , step) -> can also generate the float number in certian range

In [5]:
# numpy's arange function can also take float values 
list(np.arange(0.4 , 2.4 , 0.2))

[0.4,
 0.6000000000000001,
 0.8000000000000002,
 1.0000000000000002,
 1.2000000000000002,
 1.4000000000000004,
 1.6000000000000005,
 1.8000000000000003,
 2.0000000000000004,
 2.2000000000000006]

---

#### np.linspace(start , end , number_of_data)
#### np.logspace(start , end , number_of_data , base = 2 or 10)

In [6]:
# generator 20 data between 1 to 4 
np.linspace(1,4,20)

array([1.        , 1.15789474, 1.31578947, 1.47368421, 1.63157895,
       1.78947368, 1.94736842, 2.10526316, 2.26315789, 2.42105263,
       2.57894737, 2.73684211, 2.89473684, 3.05263158, 3.21052632,
       3.36842105, 3.52631579, 3.68421053, 3.84210526, 4.        ])

In [7]:
np.logspace(1,5,10,base=2)

array([ 2.        ,  2.72158   ,  3.70349885,  5.0396842 ,  6.85795186,
        9.33223232, 12.69920842, 17.28095582, 23.51575188, 32.        ])

---

#### np.zeros(dimension) -> to generate the zero array.
#### np.ones(dimension) -> to generate the one array.

In [8]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [9]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
# dimension -> (2d array , rows , column)
np.zeros((3,4,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [11]:
# 3 3d-matrix , 4 2d-matrix , 2 rows , 3 columns
np.ones((3,4,2,3))

array([[[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]],


       [[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]],


       [[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]]])

In [12]:
np.ones((3,2)) + 4

array([[5., 5.],
       [5., 5.],
       [5., 5.]])

In [13]:
np.ones((3,2)) * 3

array([[3., 3.],
       [3., 3.],
       [3., 3.]])

---

#### np.empty(dimension) -> to generate the empty array this will point to the previous array if present else zero nd-array.
#### np.eye(dimension) -> to generate the identity matrix.

In [14]:
arr1 = np.eye(5)
arr1

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [15]:
arr2 = np.empty((3,2))
arr2

array([[3., 3.],
       [3., 3.],
       [3., 3.]])

---

### Can convert generated array into dataframe

In [16]:
import pandas as pd 
pd.DataFrame(arr1)

0    1    2    3    4
0  1.0  0.0  0.0  0.0  0.0
1  0.0  1.0  0.0  0.0  0.0
2  0.0  0.0  1.0  0.0  0.0
3  0.0  0.0  0.0  1.0  0.0
4  0.0  0.0  0.0  0.0  1.0

---

### To generate the random data
1. rand -> mean can be anything.
2. randn -> mean will be 0.
3. randint -> integer data in the range.

In [17]:
# generate the data randomly
# mean can be anything
np.random.rand(2,3)

array([[0.32437977, 0.25282519, 0.51070319],
       [0.98040431, 0.7230827 , 0.5587065 ]])

In [18]:
# it will generate the data on standard normal diveation
# mean will be 0
np.random.randn(2,3)

array([[ 0.4696391 , -0.50226676,  0.20112147],
       [-0.78960222, -0.91915964,  0.46267692]])

In [19]:
arr3 = np.random.randint(2,8,(3,4))
print(arr3)
print(arr3.size)
print(arr3.shape)

[[7 2 4 4]
 [6 2 3 5]
 [4 2 6 3]]
12
(3, 4)


---

### Can reshape the array 
Note : Number of data should be same in both the array.

In [20]:
arr4 = arr3.reshape(12)
print(arr4)
print(arr4.shape)

[7 2 4 4 6 2 3 5 4 2 6 3]
(12,)


In [21]:
# may be 4 rows and auto columns
arr3.reshape(4,-1)

array([[7, 2, 4],
       [4, 6, 2],
       [3, 5, 4],
       [2, 6, 3]])

In [22]:
# may be 2 and 6 columns if possible
arr3.reshape(2,-16)

array([[7, 2, 4, 4, 6, 2],
       [3, 5, 4, 2, 6, 3]])

In [23]:
# may be 2 rows and 16 columns if possible
arr3.reshape(2,-16)

array([[7, 2, 4, 4, 6, 2],
       [3, 5, 4, 2, 6, 3]])

---

### Filter the array 

In [24]:
arr5 = np.random.randint(1,10,(3,5))
arr5

array([[3, 2, 6, 1, 3],
       [5, 7, 6, 2, 7],
       [1, 4, 9, 5, 8]])

In [25]:
# Filter the array to the number greater than 5
arr5 > 5

array([[False, False,  True, False, False],
       [False,  True,  True, False,  True],
       [False, False,  True, False,  True]])

In [26]:
# Give an elements of the array greater than 5
arr6 = arr5[arr5 > 5]
arr6

array([6, 7, 6, 7, 9, 8])

In [27]:
arr5

array([[3, 2, 6, 1, 3],
       [5, 7, 6, 2, 7],
       [1, 4, 9, 5, 8]])

In [28]:
# give first 2 elements
arr5[0,[0,1]]

array([3, 2])

In [29]:
arr5[1:4 , [2,3]]

array([[6, 2],
       [9, 5]])

---

### Arithmatic operation

In [30]:
arr1 = np.random.randint(1,4,(3,3))
arr2 = np.random.randint(4,8,(3,3))
print(arr1)
print()
print(arr2)

[[3 3 2]
 [2 3 2]
 [1 3 1]]

[[6 4 5]
 [7 4 4]
 [4 4 7]]


In [31]:
arr1 + arr2

array([[9, 7, 7],
       [9, 7, 6],
       [5, 7, 8]])

In [32]:
arr1 - arr2

array([[-3, -1, -3],
       [-5, -1, -2],
       [-3, -1, -6]])

In [33]:
arr1 * arr2

array([[18, 12, 10],
       [14, 12,  8],
       [ 4, 12,  7]])

In [34]:
arr1 / arr2

array([[0.5       , 0.75      , 0.4       ],
       [0.28571429, 0.75      , 0.5       ],
       [0.25      , 0.75      , 0.14285714]])

In [35]:
# matrix multiplication
arr1 @ arr2

array([[47, 32, 41],
       [41, 28, 36],
       [31, 20, 24]])

In [36]:
arr1 / 0

C:\Users\darsh\AppData\Local\Temp\ipykernel_28956\824215542.py:1: RuntimeWarning: divide by zero encountered in true_divide
  arr1 / 0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

---

### Broadcasting

In [37]:
arr = np.zeros((3,4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [38]:
# changing all the element at a time broadcast the array
arr + 5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [39]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [40]:
arr + a

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

---

### Other functions

In [41]:
b = np.random.randint(1,10,(3,3))
b

array([[1, 8, 2],
       [4, 5, 3],
       [9, 1, 3]])

In [42]:
b.T

array([[1, 4, 9],
       [8, 5, 1],
       [2, 3, 3]])

In [43]:
np.sqrt(b)

array([[1.        , 2.82842712, 1.41421356],
       [2.        , 2.23606798, 1.73205081],
       [3.        , 1.        , 1.73205081]])

In [44]:
np.log10(b)

array([[0.        , 0.90308999, 0.30103   ],
       [0.60205999, 0.69897   , 0.47712125],
       [0.95424251, 0.        , 0.47712125]])

In [45]:
np.exp(b)

array([[2.71828183e+00, 2.98095799e+03, 7.38905610e+00],
       [5.45981500e+01, 1.48413159e+02, 2.00855369e+01],
       [8.10308393e+03, 2.71828183e+00, 2.00855369e+01]])

In [46]:
np.min(b)

1

In [47]:
np.max(b)

9

In [48]:
np.mean(b)

4.0

---