# <font color = 'orange'> Numpy - Part 3

---

In [1]:
import numpy as np

In [2]:
arr = np.random.randint(1,10,(4,4))
arr

array([[7, 7, 9, 2],
       [3, 9, 4, 4],
       [2, 6, 1, 6],
       [5, 4, 5, 4]])

In [3]:
arr.reshape(8,2)

array([[7, 7],
       [9, 2],
       [3, 9],
       [4, 4],
       [2, 6],
       [1, 6],
       [5, 4],
       [5, 4]])

In [4]:
arr.T

array([[7, 3, 2, 5],
       [7, 9, 6, 4],
       [9, 4, 1, 5],
       [2, 4, 6, 4]])

---

### Convert into dimension

In [5]:
# Converting into 1 D array 
arr.flatten()

array([7, 7, 9, 2, 3, 9, 4, 4, 2, 6, 1, 6, 5, 4, 5, 4])

In [6]:
# Converting into 1 higher dimension
np.expand_dims(arr,axis=1)

array([[[7, 7, 9, 2]],

       [[3, 9, 4, 4]],

       [[2, 6, 1, 6]],

       [[5, 4, 5, 4]]])

In [7]:
# rowise convertion
np.expand_dims(arr,axis=0)

array([[[7, 7, 9, 2],
        [3, 9, 4, 4],
        [2, 6, 1, 6],
        [5, 4, 5, 4]]])

In [8]:
data = np.array([[1],[2],[3]])
data

array([[1],
       [2],
       [3]])

In [9]:
np.squeeze(data)

array([1, 2, 3])

In [10]:
np.repeat(data,4)

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3])

In [11]:
# it is like rotate
np.roll(data,1)

array([[3],
       [1],
       [2]])

In [12]:
# array with diagonal element
np.diag(np.array([1,2,3,4]))

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

---

### Arithmatic operation

In [13]:
arr1 = np.random.randint(1,10 , (3,4))
arr2 = np.random.randint(1,10 , (3,4))
print(arr1)
print()
print(arr2)

[[9 7 4 8]
 [8 7 3 2]
 [5 8 5 7]]

[[9 1 8 3]
 [3 4 1 2]
 [4 9 6 8]]


In [14]:
arr1 ** arr2

array([[387420489,         7,     65536,       512],
       [      512,      2401,         3,         4],
       [      625, 134217728,     15625,   5764801]], dtype=int32)

In [15]:
~ arr1

array([[-10,  -8,  -5,  -9],
       [ -9,  -8,  -4,  -3],
       [ -6,  -9,  -6,  -8]], dtype=int32)

In [16]:
arr1 > arr2

array([[False,  True, False,  True],
       [ True,  True,  True, False],
       [ True, False, False, False]])

---

### String function

In [17]:
arr = np.array(['sudh kumar','krish naik'])
arr

array(['sudh kumar', 'krish naik'], dtype='<U10')

In [18]:
np.char.upper(arr)

array(['SUDH KUMAR', 'KRISH NAIK'], dtype='<U10')

In [19]:
np.char.capitalize(arr)

array(['Sudh kumar', 'Krish naik'], dtype='<U10')

In [20]:
np.char.title(arr)

array(['Sudh Kumar', 'Krish Naik'], dtype='<U10')

---

### Mathematical functions

In [21]:
arr1

array([[9, 7, 4, 8],
       [8, 7, 3, 2],
       [5, 8, 5, 7]])

In [22]:
np.sin(arr1)

array([[ 0.41211849,  0.6569866 , -0.7568025 ,  0.98935825],
       [ 0.98935825,  0.6569866 ,  0.14112001,  0.90929743],
       [-0.95892427,  0.98935825, -0.95892427,  0.6569866 ]])

In [23]:
np.cos(arr1)

array([[-0.91113026,  0.75390225, -0.65364362, -0.14550003],
       [-0.14550003,  0.75390225, -0.9899925 , -0.41614684],
       [ 0.28366219, -0.14550003,  0.28366219,  0.75390225]])

In [24]:
np.tan(arr1)

array([[-0.45231566,  0.87144798,  1.15782128, -6.79971146],
       [-6.79971146,  0.87144798, -0.14254654, -2.18503986],
       [-3.38051501, -6.79971146, -3.38051501,  0.87144798]])

In [25]:
np.log10(arr1)

array([[0.95424251, 0.84509804, 0.60205999, 0.90308999],
       [0.90308999, 0.84509804, 0.47712125, 0.30103   ],
       [0.69897   , 0.90308999, 0.69897   , 0.84509804]])

In [26]:
np.exp(arr1)

array([[8.10308393e+03, 1.09663316e+03, 5.45981500e+01, 2.98095799e+03],
       [2.98095799e+03, 1.09663316e+03, 2.00855369e+01, 7.38905610e+00],
       [1.48413159e+02, 2.98095799e+03, 1.48413159e+02, 1.09663316e+03]])

In [27]:
np.power(arr1,2)

array([[81, 49, 16, 64],
       [64, 49,  9,  4],
       [25, 64, 25, 49]], dtype=int32)

---

### Stats

In [28]:
arr1

array([[9, 7, 4, 8],
       [8, 7, 3, 2],
       [5, 8, 5, 7]])

In [29]:
np.mean(arr1)

6.083333333333333

In [30]:
np.median(arr2)

4.0

In [31]:
# standard deviation - it is a dispersion from the mean
np.std(arr1)

2.1392496088322392

In [32]:
# variance
np.var(arr1)

4.576388888888888

In [33]:
np.min(arr1)

2

In [34]:
np.max(arr1)

9

---

### Arithmetic operations

In [35]:
print(arr1)
print()
print(arr2)

[[9 7 4 8]
 [8 7 3 2]
 [5 8 5 7]]

[[9 1 8 3]
 [3 4 1 2]
 [4 9 6 8]]


In [36]:
arr1 - arr2

array([[ 0,  6, -4,  5],
       [ 5,  3,  2,  0],
       [ 1, -1, -1, -1]])

In [37]:
np.subtract(arr1,arr2)

array([[ 0,  6, -4,  5],
       [ 5,  3,  2,  0],
       [ 1, -1, -1, -1]])

In [38]:
np.multiply(arr1,arr2)

array([[81,  7, 32, 24],
       [24, 28,  3,  4],
       [20, 72, 30, 56]])

In [39]:
np.mod(arr1,arr2)

array([[0, 0, 4, 2],
       [2, 3, 0, 0],
       [1, 8, 5, 7]], dtype=int32)

In [40]:
np.power(arr1,arr2)

array([[387420489,         7,     65536,       512],
       [      512,      2401,         3,         4],
       [      625, 134217728,     15625,   5764801]], dtype=int32)

---